// lib/questionCategories.js

export const questionCategories = {
  icebreakers: {
    name: 'Icebreakers',
    icon: 'Sparkles',
    description: 'Light, fun questions to get everyone talking',
    color: 'from-blue-400 to-cyan-400',
    questions: [
      "If you could have any superpower for just one day, what would you do with it?",
      "What's the weirdest food combination you actually enjoy?",
      "If you could instantly become an expert at any skill, what would you choose?",
      "What's something you believed as a kid that makes you laugh now?",
      "If you could have dinner with any fictional character, who would it be?",
      "What's the most useless talent you have?",
      "If you could rename yourself, what name would you choose?",
      "What's the strangest compliment you've ever received?",
      "If you could live in any TV show universe, which would you pick?",
      "What's something everyone seems to love that you just don't get?",
      "If you could ask your pet one question, what would it be?",
      "What's the most embarrassing thing you've googled?",
      "If you could swap lives with anyone for a week, who would it be?",
      "What's a skill you wish was taught in school but wasn't?",
      "If you could make one rule that everyone had to follow, what would it be?",
      "What's the most ridiculous thing you've convinced someone was true?",
      "If you could eliminate one minor inconvenience from daily life, what would it be?",
      "What's your most irrational fear that you're secretly embarrassed about?",
      "If you had to wear a warning label, what would it say?",
      "What's the weirdest dream you remember having?",
      "If you could add a 13th month to the year, what would you name it?",
      "What's something you do when you're alone that you'd never do in front of others?",
      "If you could make any activity an Olympic sport, what would you win gold in?",
      "What's the most unusual thing you find attractive?",
      "If you had to live in a world made of one food, what food would you choose?"
    ]
  },
  deep_dive: {
    name: 'Deep Dive',
    icon: 'Heart',
    description: 'Meaningful questions for genuine connection',
    color: 'from-purple-400 to-pink-400',
    questions: [
      "What's a belief you held strongly as a child that you've completely changed your mind about?",
      "What's the most important lesson you've learned about yourself in the past year?",
      "If you could send a message to your past self, what age would you choose and what would you say?",
      "What's something you're secretly proud of but rarely talk about?",
      "What fear have you overcome that you're most grateful for conquering?",
      "What's a conversation you've been avoiding that you know you need to have?",
      "What's something about yourself that you hope never changes?",
      "If you knew you couldn't fail, what would you attempt?",
      "What's the kindest thing someone has ever done for you?",
      "What do you wish people understood about you without you having to explain it?",
      "What's a moment when you felt most proud of who you are?",
      "What's something you've forgiven yourself for that was hard to let go?",
      "What would you want to be remembered for?",
      "What's a risk you took that taught you something important about yourself?",
      "What's the most valuable piece of advice you've received but initially ignored?",
      "What's a hard truth about yourself that you've recently accepted?",
      "What's the biggest sacrifice you've made that no one knows about?",
      "What childhood wound still affects how you show up in relationships today?",
      "What's something you need to hear but no one has told you?",
      "What part of your personality do you think people misunderstand the most?",
      "What's a dream you've given up on and why?",
      "What would your life look like if you weren't afraid of judgment?",
      "What's the most honest thing you've never said to someone you love?",
      "What do you think you'll regret not doing when you're 80?",
      "What's a pattern in your life that you're finally ready to break?"
    ]
  },
  creative: {
    name: 'Creative & Imaginative',
    icon: 'Lightbulb',
    description: 'Fun hypotheticals and creative scenarios',
    color: 'from-yellow-400 to-orange-400',
    questions: [
      "If you could design a new holiday, what would it celebrate and how would people observe it?",
      "You can time travel but only to observe, not change anything. Where/when do you go?",
      "If you could add one feature to the human body, what would make life better?",
      "You're designing a theme park. What's your signature ride or attraction?",
      "If you could make any two animals swap sounds, which would be the funniest combination?",
      "You can give everyone in the world one book to read. Which book changes everything?",
      "If you could redesign how humans sleep, what would you change?",
      "You're creating a new planet. What's one unique feature that makes it special?",
      "If you could make one everyday object sentient, what would be most interesting?",
      "You can add background music to real life. What plays during different activities?",
      "If you could change one law of physics temporarily, what chaos would you create?",
      "You're founding a new country. What's your national motto and why?",
      "If you could give everyone a new sense (beyond the five we have), what would it be?",
      "You can make one extinct animal come back to life. What's your choice and why?",
      "If you could redesign the concept of money, what would the new system look like?",
      "If you could create a new emotion that doesn't exist, what would it feel like?",
      "You can merge any two companies. Which merger would create the most chaos?",
      "If you had to design hell for someone you dislike, what would their personal hell be?",
      "You can make one conspiracy theory actually true. Which one do you choose?",
      "If you could add a new mandatory subject to all schools, what would teach kids?",
      "You can make one body part detachable. Which would be most convenient?",
      "If you could create a new sport using items from your kitchen, what would it be?",
      "You can make one animal as intelligent as humans. Which causes the most drama?",
      "If you could add a new day between Saturday and Sunday, how would people spend it?",
      "You can make one fictional technology real. What do you choose and why?"
    ]
  },
  spicy: {
    name: 'Spicy',
    icon: 'Flame',
    description: 'Bold questions for adventurous groups',
    color: 'from-red-400 to-pink-400',
    questions: [
      "What's something you've never told anyone but would feel relieved to share?",
      "What's the most embarrassing thing you've done when you had a crush on someone?",
      "If you could read minds for one day, whose thoughts would you be most curious about?",
      "What's a secret skill or talent you have that would surprise people?",
      "What's the most rebellious thing you've ever done?",
      "If you could anonymously tell someone exactly what you think of them, who would it be?",
      "What's something you judge people for but probably shouldn't?",
      "What's the biggest lie you've told to avoid hurting someone's feelings?",
      "If you could erase one memory from your life, what would it be?",
      "What's something you pretend to like but actually can't stand?",
      "What's the most awkward misunderstanding you've been part of?",
      "If you could know the honest answer to any question about yourself, what would you ask?",
      "What's something you've done that you'd never want your parents to find out about?",
      "What's your most unpopular opinion that you'd defend?",
      "If you could switch lives with someone you know for 24 hours, who would you choose?",
      "What's the most inappropriate thing you've laughed at?",
      "What's your most toxic trait that you're lowkey proud of?",
      "If you could see one statistic about everyone you meet, what would you choose?",
      "What's the pettiest thing you've done that you don't regret?",
      "What's a compliment you've received that felt more like an insult?",
      "If you had to expose one person's search history, whose would be most interesting?",
      "What's something you do that you think everyone does, but you're afraid to ask?",
      "What's the most unhinged intrusive thought you've had this week?",
      "If karma is real, what's coming for you?",
      "What's the worst advice you've ever given that someone actually followed?"
    ]
  },
  growth: {
    name: 'Goals & Growth',
    icon: 'Target',
    description: 'Future-focused and aspirational questions',
    color: 'from-green-400 to-blue-400',
    questions: [
      "What's something you want to be brave enough to do in the next year?",
      "If you could master one area of your life completely, which would have the biggest impact?",
      "What's a habit you want to build that would change your daily life for the better?",
      "What's something you used to dream about that you've stopped pursuing? Why?",
      "If you could give your future self one piece of advice, what would it be?",
      "What's a skill you want to develop that would make you feel more confident?",
      "What's something you want to stop caring so much about?",
      "If you could change one thing about how you spend your time, what would it be?",
      "What's a fear you want to face head-on this year?",
      "What's something you want to create or build in your lifetime?",
      "If you could develop one character trait overnight, what would serve you best?",
      "What's a relationship in your life you want to invest more energy in?",
      "What's something you want to experience before you turn [next milestone age]?",
      "What's a way you want to challenge yourself that excites and scares you?",
      "If you could design your ideal typical day five years from now, what would it look like?",
      "What's the biggest change you need to make but keep postponing?",
      "What would you do differently if you truly believed you were enough?",
      "What's a boundary you need to set that you've been avoiding?",
      "If you had unlimited resources, what problem would you solve?",
      "What's one thing you could do tomorrow that your future self would thank you for?",
      "What part of your life needs a complete reimagining?",
      "What would you pursue if you knew your family would support you no matter what?",
      "What's the gap between who you are and who you want to be?",
      "What legacy do you want to leave for the next generation?",
      "If you could guarantee one thing for your future, what would it be?"
    ]
  },
  uncomfortable_truths: {
    name: 'Uncomfortable Truths',
    icon: 'MessageCircle',
    description: 'Questions that challenge your self-perception',
    color: 'from-gray-600 to-purple-600',
    questions: [
      "What's a harsh reality about yourself that others see but you tend to ignore?",
      "When was the last time you were the villain in someone else's story?",
      "What's something you criticize in others that you're guilty of yourself?",
      "What privilege do you have that you take for granted?",
      "What's a time you were completely wrong but too proud to admit it?",
      "What's the most selfish decision you've made that you still stand by?",
      "What truth about a relationship are you refusing to accept?",
      "What's something you do for others that's actually more about you?",
      "What excuse do you use most often to avoid growth?",
      "What's a way you manipulate situations to get what you want?",
      "What double standard do you hold that benefits you?",
      "What's something you're mediocre at but think you're good at?",
      "What uncomfortable feedback have multiple people given you that's probably true?",
      "What's a time your ego got in the way of doing the right thing?",
      "What pattern do you see in others' lives but are blind to in your own?",
      "What's the gap between how you see yourself and how others see you?",
      "What do you pretend to want but actually fear getting?",
      "What's a truth about your parents that changed how you see yourself?",
      "What part of your identity are you most attached to losing?",
      "What's the story you tell yourself to avoid taking responsibility?",
      "What would change if you stopped needing to be right?",
      "What's something you judge in your past self that you still do?",
      "What uncomfortable truth would set you free if you accepted it?",
      "What do you need to grieve that you've been avoiding?",
      "What's the cost of maintaining the image you project to the world?"
    ]
  }
};
